services:
  - type: web
    name: impossible-challenge
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
